### ------ Variables ---------

@baseUrl=https://jsonplaceholder.typicode.com
@contentType= application/json

### ----------
###    GET
### ----------

GET {{baseUrl}}/posts HTTP/1.1

### crear un POST y capturar la respuesta

POST {{baseUrl}}/posts HTTP/1.1
content-Type: {{contentType}}

{
    "title": "Titulo del POST de ejemplo",
    "body": "contenido",
    "userId": 1
}